### ISSUE TITLE
动态加载script标签会导致加载顺序错误

### ISSUE THREAD

**Issue by hua-zhi-wan** [Anjaxs/WebStack-vue#11]
经测试，使用`loadJs`函数动态载入`<script>`标签后，由于加载顺序不一致，有可能导致对jquery的扩展和引用无法正确生效。

这里放上我自己的网站做例子：

[这是改成了静态加载后生成的页面](https://ka.kaga.ga)  
[这是原先动态加载生成的界面](https://kaga-44zhgtz4z-hanayabuki.vercel.app/)

后者（在我测试的时候）的页面动效无法触发。

**Comment by hua-zhi-wan** [comment]
PS：赶紧修，不然过几天我把坏的网站取消部署咱就不方便复现bug了（doge

**Comment by Anjaxs** [comment]
感谢您的测试，问题已经修复
